apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: exclusive-access-to-helloworld2
  namespace: suresh-apps
spec:
  selector:
    matchLabels:
      app: helloworld2
  action: ALLOW
  rules:
  - from:
    - source:
        # Changed 'your-namespace-name' to 'suresh-apps'
        principals: ["cluster.local/ns/suresh-apps/sa/helloworld1-sa"]