apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sureshsy1/helloworld2.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: suresh-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
